server: 
    port: 80
    context-path: /
    tomcat:
      uri-encoding: UTF-8
logging:
  level: 
    root: info  
    path: E:/log/baron  
spring:
  datasource:
     #基本配置
    driver-class-name: com.mysql.jdbc.Driver #可以省略 会根据URL自动判断 
    url: jdbc:mysql://111.231.79.149:3306/db_test
    username: root
    password: 520520
    
  thymeleaf:
    cache: false 
     
  messages:
    basename: i18n.login
    
  mvc:
    date-format: yyyy-MM-dd   
    
  redis:
    host: 111.231.79    
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true    